name: Composite addition action evn
description: Test evn

inputs:
  token:
    description: 'A Github PAT'
    required: true

  test:
    required: true

runs:
  using: composite
  steps:
    - run: echo "git branch test"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_1: ${{ inputs.test }}
        INPUT_2: ${{ inputs.token }}
      shell: bash
